import styles from "./../styles/Home.module.css";

import { ConnectButton } from "@rainbow-me/rainbowkit";
export default function MainLayout({ children }) {
  return (
    <div className={styles.container}>
      <head>
        <title>swaym_sahayta_samuh By Naushad</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </head>

      <main className={styles.main}>
        <div className={styles.navigation}>
          <h1
            style={{
              marginLeft: "10px",
              color: "black",
              backgroundColor: "white",
              padding: "10px",
              borderRadius: "10px",
            }}
          >
            S
            <sup
              style={{
                verticalAlign: "super",
                fontSize: "smaller",
              }}
            >
              S
              <sup
                style={{
                  verticalAlign: "super",
                  fontSize: "smaller",
                }}
              >
                s
              </sup>
            </sup>
          </h1>
          <div className={styles.wallet}>
            <ConnectButton />
          </div>
        </div>
        {children}
      </main>
      {/* 
      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer> */}
    </div>
  );
}
